### ISSUE TITLE
fetch does not return

### ISSUE THREAD

**Issue by tronta** [nolanderc/rust-postgres-query#3]
First of all thanks for your work!
I have problems using your crate (caution newbie).
Unfortunately the fetch command never returns:
` let users: Vec<User> = query.fetch(&r.0).await.unwrap();`

The example in the repo is not as simple as the one on the main page.
It would be great if you could tell me how to solve the problem/provide a complete minimal example.

[test.zip](https://github.com/nolanderc/rust-postgres-query/files/4023907/test.zip

**Comment by nolanderc** [comment]
Hi! Thanks for trying out my crate!

Some notes before we get to your problem: be more careful when sharing your code in the future. The zip you linked to contained your `.env` file, containing what I assume to be your real name and password. If this is in fact your real password, I would highly recommend you change to a new/better one, as this one is now publicly available on the internet.

Onto your problem: the `Client` provided by `tokio-postgres` does nothing on its own. When a connection is established you are provided two parts: the `Client` and a `Connection`. The `Connection` is what communicates with the actual database, the `Client` simply sends requests to the associated `Connection`. To fix your example you would need to make sure the connection (contained in `r.1`) actually handles your requests by `await`ing it (sometimes referred to as "polling" it). See the first example in [`tokio-postgres`'s documentation](https://docs.rs/tokio-postgres/0.5.1/tokio_postgres/index.html). 

For a simple example, see the [examples](https://github.com/nolanderc/rust-postgres-query/tree/master/postgres_query/examples) directory.

**Comment by tronta** [comment]
Thanks a lot. Now it works. Thanks for your great crate.

Don't worry it's just a local testing db. Somehow your example in https://github.com/nolanderc/rust-postgres-query/blob/master/README.md set me on the wrong track.
