### ISSUE TITLE
Multi-mapping for one-to-many relationships

### ISSUE THREAD

**Issue by nolanderc** [nolanderc/rust-postgres-query#6]
We should support extractors which allow having one object be related to many
others. For example, having an author contain multiple books.

In order for such a feature to work we would need to specify some key to
determine if two rows reference the same object, and if they are, merge them. 

We could specify the key by adding a new field attribute: `#[row(key)]`. This
would tell us which column(s) to use for comparisons. Then we could add two new
container attributes: `#[row(group)]` and `#[row(hash)]` (not a fan of the
names, but they get the point across). The `group` attribute would only look at
the previous row and check if the key matches (as you would in a `GROUP BY`
query). With `hash` we would keep a hash-map of all keys and merge objects
that way.

Additionally, to figure out which field to merge, we could probably need another
attribute: `#[row(merge)]`. For a trait to be able to be merged it should
implement the [`Extend<T>`](https://doc.rust-lang.org/std/iter/trait.Extend.html) trait.

For example:

```rust
#[derive(FromSqlRow)]
#[row(split, group)]
struct Author {
    #[row(split = "id", key)]
    id: i32,
    name: String,
    
    #[row(split = "id", merge)]
    books: Vec<Book>,
}

#[derive(FromSqlRow)]
struct Book {
    id: i32,
    title: String,
    genre: String,
}
```

**Comment by AviiNL** [comment]
I don't understand how this works, doesn't Book need some reference to author? like an `author_id: i32` or even an `author: Author` column?
How does this know *which* books to select for each author?
Maybe an SQL snippet of the table structures might clear this up.

**Comment by nolanderc** [comment]
@AviiNL The corresponding query for these two structures would be something along the lines of: 
```sql
SELECT author.id, author.name, book.id, book.title, book.genre
FROM authors INNER JOIN books ON author.id = book.author
```
This would produce a table on the form `id | name | id | title | genre`. Using the `#[row(split = ...)]` annotations we disambiguate which `id` correspond to the author, and which corresponds to the book (based on the order in which they occur). Note that we don't include the `book.author` in the `SELECT` part of the query, but it's still there for the `JOIN`. Figuring out how to group the authors and books can be inferred from each row as follows:

All rows returned by this query are merged based on the `#[row(key)]` and `#[row(merge)]` annotations: all rows with the same key (in this case `author.id`) get grouped together, and if there are conflicts on the other columns, they are either ignored (the default, which is happening to `author.name`) or merged together into a collection (if there is an `#[row(merge)]` attribute, which is the case for the books).

Does that answer your question?
